typedef struct t_DX12DESCRIPTORHANDLE {
  D3D12_CPU_DESCRIPTOR_HANDLE cpuhandle;
  D3D12_GPU_DESCRIPTOR_HANDLE gpuhandle;
} DX12DESCRIPTORHANDLE;

typedef struct t_DX12DESCRIPTORHEAP {
  U32 count;
  U32 usedcount;
  D3D12_DESCRIPTOR_HEAP_TYPE type;
  U8 unused0[4];
  ID3D12DescriptorHeap *heap;
} DX12DESCRIPTORHEAP;