#define RESOURCE_WORLD0 100
#define RESOURCE_TYPE_WORLD 101
#define RESOURCE_SHADER_VERTEX 102
#define RESOURCE_SHADER_PIXEL 103
#define RESOURCE_DEFAULT_VERTEX 104
#define RESOURCE_DEFAULT_PIXEL 105
#define RESOURCE_TYPE_HLSL 106
